server:
  port: 8010

spring:
  application:
    name: ws-retail-apigateway

  cloud:
    gateway:
      globalcors:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - Content-Type

      routes:
        - id: ws-retail-itemservice
          uri: http://ws-retail-itemservice:8009
          predicates:
            - Path=/api/item/**

        - id: ws-retail-orderservice
          uri: http://ws-retail-orderservice:8008
          predicates:
            - Path=/api/order/**

        - id: ws-retail-authenticationservice
          uri: http://ws-retail-authenticationservice:8007
          predicates:
            - Path=/api/v1/auth/**
